/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdo;

import bdo.connection.OracleCon;
import java.util.List;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import oracle.sql.DATE;

/**
 *
 * @author ORACLE
 */
public class AjouterNote extends javax.swing.JFrame {

    /**
     * Creates new form AjouterNote
     */
    String module;
    public AjouterNote() throws SQLException, SQLException {
       
        initComponents();
        this.filieres();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        modules = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        filieres = new javax.swing.JComboBox<>();
        Path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Reser = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        elements = new javax.swing.JComboBox<>();
        Reser1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        logo.setForeground(new java.awt.Color(0, 0, 204));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("Ajouter des notes à un module ");

        jTextField2.setText("Module");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        modules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        modules.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modulesItemStateChanged(evt);
            }
        });

        jTextField1.setText("Filiere");

        filieres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        filieres.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filieresItemStateChanged(evt);
            }
        });
        filieres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filieresActionPerformed(evt);
            }
        });

        jButton1.setText("Import CSV FILE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        Reser.setBackground(new java.awt.Color(255, 51, 51));
        Reser.setText("Reset");

        jTextField4.setText("element");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        elements.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        elements.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                elementsItemStateChanged(evt);
            }
        });

        Reser1.setBackground(java.awt.Color.green);
        Reser1.setText("Exportee vers BDD");
        Reser1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Reser1ItemStateChanged(evt);
            }
        });
        Reser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reser1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Path, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(elements, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(filieres, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(modules, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Reser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Reser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filieres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Path, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(14, 14, 14)
                .addComponent(Reser1)
                .addGap(18, 18, 18)
                .addComponent(Reser)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void modulesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modulesItemStateChanged
        try {
            this.elements(evt.getItem().toString());

        } catch (SQLException ex) {
            Logger.getLogger(AjouterNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modulesItemStateChanged

    private void filieresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filieresItemStateChanged

        try {
            this.modules(evt.getItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(AjouterNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_filieresItemStateChanged

    private void filieresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filieresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filieresActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
             JFileChooser chooser=new JFileChooser();
             chooser.addChoosableFileFilter(new FileNameExtensionFilter("CSV FILES (*.csv)", "*.csv"));
             chooser.showSaveDialog(null);
             File f=chooser.getSelectedFile();
            if(f!=null){
            Path.setText(f.getAbsolutePath());

            }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void elementsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_elementsItemStateChanged
      
    }//GEN-LAST:event_elementsItemStateChanged

    private void Reser1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Reser1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Reser1ItemStateChanged

    private void Reser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reser1MouseClicked
        File file=new File(Path.getText());
        List<String> lignes=new ArrayList<String>();
        try{
            Scanner scanner=new Scanner(file);
            while(scanner.hasNext()){
            lignes.add(scanner.next());
            
            
            }
            this.prepareNote(lignes);
        }
        catch(FileNotFoundException e ){
        e.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(AjouterNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Reser1MouseClicked

    
    public void prepareNote(List<String> lignes) throws SQLException{
     for(int i=0;i<lignes.size();i++){
        String plsql ="insert into  notes values(?,?,(select ref(e) from etudiants e where e.cne=?),(select ref(e) from elements e where e.nom=?))";
        CallableStatement cs;   
        String ligne[]=new String[10];
        ligne=lignes.get(i).split(",");
            try {
                cs = OracleCon.getInstance().getConnexion().prepareCall(plsql);
                cs.setString(1,ligne[0]);
                cs.setString(2,ligne[1]);
                cs.setString(3, ligne[2]);
                cs.setString(4,ligne[3]);
                cs.execute();
            }
             catch (SQLException ex) {
                Logger.getLogger(InsertionEtudiant.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
            }
     }
    }
      public void filieres() throws SQLException{
       
        String plsql ="select * from filieres";
        CallableStatement cs= OracleCon.getInstance().getConnexion().prepareCall(plsql);   
        cs.execute();
        ResultSet rs=(ResultSet) cs.getResultSet();
        while(rs.next()){
        this.filieres.addItem(rs.getString("nom"));
        }
         }
     public void modules(String f) throws SQLException{
       String plsql ="select * from modules where deref(ref_filiere).nom=?";
        CallableStatement cs= OracleCon.getInstance().getConnexion().prepareCall(plsql);   
        cs.setString(1, f);
        cs.execute();
        ResultSet rs=(ResultSet) cs.getResultSet();
        while(rs.next()){
        this.modules.addItem(rs.getString("nom"));
        }
     }
     public void elements(String m) throws SQLException{
       String plsql ="select * from elements where deref(refmodule).nom=?";
        CallableStatement cs= OracleCon.getInstance().getConnexion().prepareCall(plsql);   
        cs.setString(1, m);
        cs.execute();
        ResultSet rs=(ResultSet) cs.getResultSet();
        while(rs.next()){  
        this.elements.addItem(rs.getString("nom"));
        }
     }
     
     
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AjouterNote().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AjouterNote.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Path;
    private javax.swing.JButton Reser;
    private javax.swing.JButton Reser1;
    private javax.swing.JComboBox<String> elements;
    private javax.swing.JComboBox<String> filieres;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> modules;
    // End of variables declaration//GEN-END:variables
}
