/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdo;

import bdo.connection.OracleCon;
import bdo.entities.Etudiant;
import bdo.entities.Personne;
import java.awt.event.WindowEvent;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ORACLE
 */
public class Gerer_etudiants extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Gerer_etudiants() throws SQLException {
        initComponents();
        this.loaddatatotable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cne = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableetudiants = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        niveau = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        filieresliste = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("cne");

        jLabel3.setText("nom");

        jLabel4.setText("prenom");

        ajouter.setText("Ajouter");
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        modifier.setText("Modifier");
        modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifierMouseClicked(evt);
            }
        });

        supprimer.setText("Supprimer");
        supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerMouseClicked(evt);
            }
        });
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        tableetudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cne", "nom", "prenom", "email", "niveau", "filiere"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableetudiants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableetudiantsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableetudiants);

        jLabel5.setText("email");

        jLabel1.setText("filiere");

        jLabel6.setText("niveau");

        reset.setBackground(new java.awt.Color(255, 0, 0));
        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setText("Liste des étudiants");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cne, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(niveau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(nom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(filieresliste, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ajouter)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(supprimer)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(filieresliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifier)
                            .addComponent(ajouter)
                            .addComponent(supprimer))
                        .addGap(18, 18, 18)
                        .addComponent(reset)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableetudiantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableetudiantsMouseClicked
         int i=this.tableetudiants.getSelectedRow();
         TableModel model=this.tableetudiants.getModel();
         this.nom.setText(model.getValueAt(i,1).toString());
         this.prenom.setText(model.getValueAt(i,2).toString());
         this.cne.setText(model.getValueAt(i,0).toString());
         this.email.setText(model.getValueAt(i,3).toString());

         this.niveau.setValue(model.getValueAt(i,4));
          
    }//GEN-LAST:event_tableetudiantsMouseClicked

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked
        try {
            InsertionEtudiant insertion=new InsertionEtudiant();
            insertion.show();
            insertion.setDefaultCloseOperation(EXIT_ON_CLOSE);
            insertion.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    try {
                        loaddatatotable();
                        insertion.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    } catch (SQLException ex) {
                        Logger.getLogger(Gerer_etudiants.class.getName()).log(Level.SEVERE, null, ex);
                    }
                   
                }
               
            
            });
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Gerer_etudiants.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_ajouterMouseClicked

    private void modifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifierMouseClicked
       String cin=this.cne.getText();
       String email=this.email.getText();
       String nom=this.getNom().getText();
       String prenom=this.getPrenom().getText();
       int niveau =(int) this.niveau.getValue();
       String deleteetudiant = 
        " declare " +  
        "   obj t_etudiant:=t_etudiant(?,?,?,?,?,?,?,?,?,null);" +
        "    n number;" +
        " begin " +
        "   n:=obj.updateetudiant(obj);" +
        "    ? := n; commit;" +
        " end;";
        CallableStatement cs=null;
        try {
            cs = OracleCon.getInstance().getConnexion().prepareCall(deleteetudiant);
            cs.setString(1, nom);         
            cs.setString(2, prenom);
            cs.setString(3,"FES");
            cs.setString(4,"11/11/2011");
            cs.setString(5,cin);
            cs.setString(6,"phone");
            cs.setString(7, email);
            cs.setString(8, cin);
            cs.setInt(9, niveau);
        cs.registerOutParameter(10, Types.NUMERIC);
        cs.execute();
        System.out.println("Result = " + cs.getObject(10));
        this.loaddatatotable();
        cs.close(); 
        this.loaddatatotable();
        } catch (SQLException ex) {
            Logger.getLogger(Gerer_etudiants.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modifierMouseClicked

    private void supprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerMouseClicked
        String cin=this.getCne().getText();
                
        String deleteetudiant = 
        " declare " +  
        "    obj t_etudiant := t_etudiant();" +
        "    n number;" +
        " begin " +
        "   n:=obj.deleteperson(?);" +
        "    ? := n; commit;" +
        " end;";
         CallableStatement cs=null;
        try {
            cs = OracleCon.getInstance().getConnexion().prepareCall(deleteetudiant);
            cs.setString(1, cin);
        cs.registerOutParameter(2, Types.NUMERIC);
        cs.execute();
        System.out.println("Result = " + cs.getObject(2));
        this.loaddatatotable();
        cs.close(); 
        } catch (SQLException ex) {
            Logger.getLogger(Gerer_etudiants.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_supprimerMouseClicked

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        this.cne.setText("");
        this.nom.setText("");
        this.prenom.setText("");
        this.email.setText("");
        this.niveau.setValue(1);
        try {
            this.loaddatatotable();
        } catch (SQLException ex) {
            Logger.getLogger(Gerer_etudiants.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerer_etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerer_etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerer_etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerer_etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Gerer_etudiants().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Gerer_etudiants.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JTextField cne;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> filieresliste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifier;
    private javax.swing.JSpinner niveau;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JButton reset;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tableetudiants;
    // End of variables declaration//GEN-END:variables

    public JTextField getNom() {
        return nom;
    }

    public JTextField getPrenom() {
        return prenom;
    }

    public JTextField getCne() {
        return cne;
    }

    public JTextField getEmail() {
        return email;
    }

    public void setEmail(JTextField email) {
        this.email = email;
    }

    public void setCne(JTextField cne) {
        this.cne = cne;
    }

    public void setNom(JTextField nom) {
        this.nom = nom;
    }

    public void setPrenom(JTextField prenom) {
        this.prenom = prenom;
    }

    
    public ArrayList<Etudiant> loaddata() throws SQLException{
        String plsql ="select * from etudiants";
        String plsql2 ="select deref(ref_filiere).nom as nom as filiere from etudiants";
        CallableStatement cs= OracleCon.getInstance().getConnexion().prepareCall(plsql);   
        CallableStatement cs1= OracleCon.getInstance().getConnexion().prepareCall(plsql);        
        cs.execute();
        cs1.execute();
        ResultSet rs=(ResultSet) cs.getResultSet();
        ResultSet rs1=(ResultSet) cs1.getResultSet();
        ArrayList<Etudiant> etudiants=new ArrayList<>();
        while(rs.next()){
            rs1.next();
        Etudiant e=new Etudiant( rs.getString("firstname"), rs.getString("lastname"), rs.getString("cin"), rs.getString("email"),rs1.getString(1),rs.getInt("niveau"));
        etudiants.add(e);
        System.err.println(e.toString());
        }
        if(etudiants.size()==0)
            return null;
        return etudiants;
    }
    

    public  void loaddatatotable() throws SQLException, SQLException{
    if(this.loaddata()!=null){
        DefaultTableModel model=(DefaultTableModel) this.tableetudiants.getModel();
        model.setRowCount(0);
        Object[] row=new Object[6];
        ArrayList<Etudiant> etudiants=this.loaddata();
        for(int i=0;i<this.loaddata().size();i++){
        row[1]=etudiants.get(i).getNom();
        row[2]=etudiants.get(i).getPrenom();
        row[0]=etudiants.get(i).getCne();
        row[3]=etudiants.get(i).getEmail();
        row[4]=etudiants.get(i).getNiveau();
        row[5]=etudiants.get(i).getFiliere();

        model.addRow(row);
        }
    }
    else{
          DefaultTableModel model=(DefaultTableModel)  tableetudiants.getModel();
          model.setRowCount(0);
            return;

    }
    }
    
    
    
    


}
