/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdo;

import bdo.connection.OracleCon;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author ORACLE
 */
public class Notes extends javax.swing.JFrame {

    /**
     * Creates new form Notes
     */
    int niveau=1;
   
    public Notes() throws SQLException {
        initComponents();
        this.filieres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filieres = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablenotes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableetudiants = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        resultat = new javax.swing.JLabel();
        annees = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        annee1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filieres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        filieres.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filieresItemStateChanged(evt);
            }
        });
        filieres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filieresActionPerformed(evt);
            }
        });

        jTextField1.setText("Filiere");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Etudinats");

        tablenotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "module", "Nombre elements", "notes", "année"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablenotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenotesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablenotes);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Notes");

        tableetudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cne", "nom", "prenom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableetudiants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableetudiantsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableetudiants);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Resultat");

        annees.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ère année", "2ème  année", "3ème année", " " }));
        annees.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                anneesItemStateChanged(evt);
            }
        });

        jLabel3.setText("Annee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(filieres, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(annees, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(annee1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(721, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(213, 213, 213)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(645, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(284, 284, 284)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(772, Short.MAX_VALUE)
                    .addComponent(resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(120, 120, 120)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filieres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(annee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(459, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(428, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(102, 102, 102)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(428, Short.MAX_VALUE)
                    .addComponent(resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(89, 89, 89)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filieresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filieresItemStateChanged
        
        try {
            this.etudiants(filieres.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_filieresItemStateChanged

    private void filieresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filieresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filieresActionPerformed

    private void tablenotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenotesMouseClicked

        /* this.nom.setText(model.getValueAt(i,1).toString());
        this.prenom.setText(model.getValueAt(i,2).toString());
        this.cne.setText(model.getValueAt(i,0).toString());
        this.email.setText(model.getValueAt(i,3).toString());
        this.filiere.setText(model.getValueAt(i,5).toString());
        this.niveau.setValue(model.getValueAt(i,4));
        */
    }//GEN-LAST:event_tablenotesMouseClicked

    private void tableetudiantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableetudiantsMouseClicked
         int i=this.tableetudiants.getSelectedRow();
         System.out.println("hdblj");
         TableModel model=this.tableetudiants.getModel();
        try {
            this.notes(model.getValueAt(i,0).toString());
                     System.out.println(model.getValueAt(i,0).toString());

        } catch (SQLException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_tableetudiantsMouseClicked

    private void anneesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_anneesItemStateChanged
               
        switch(this.annees.getSelectedIndex()){
            case 0:        this.niveau=1;break;
            case 1:        this.niveau=2;break;
            case 2:        this.niveau=3;break;
        }
        try {
            this.etudiants(this.filieres.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_anneesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Notes().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

     public void filieres() throws SQLException{
       
        String plsql ="select * from filieres";
        CallableStatement cs= OracleCon.getInstance().getConnexion().prepareCall(plsql);   
        cs.execute();
        ResultSet rs=(ResultSet) cs.getResultSet();
        while(rs.next()){
        this.filieres.addItem(rs.getString("nom"));
        }
         }
     
     
     public void etudiants(String f) throws SQLException{
         String plsql ="select lastname,firstname,cne from etudiants  where deref(ref_filiere).nom=? and niveau =?";
        CallableStatement cs= OracleCon.getInstance().getConnexion().prepareCall(plsql);   
        cs.setString(1, f);
        cs.setInt(2, this.niveau);
        cs.execute();
        ResultSet rs=(ResultSet) cs.getResultSet();
        DefaultTableModel model=(DefaultTableModel) this.tableetudiants.getModel();
        model.setRowCount(0);
        while(rs.next()){
        Object[] row=new Object[3];
        row[0]=rs.getString("cne");
        row[1]=rs.getString("lastname");
        row[2]=rs.getString("firstname");
        model.addRow(row);        
}
     }
      
     public void notes(String f) throws SQLException{
         String deleteetudiant = 
        " declare " +  
        "    obj t_etudiant := t_etudiant(); "
         + "l_rc sys_refcursor ;" +
        " begin " +
        "   l_rc:=obj.getNotes(?,?);" +
        "    ? := l_rc; commit;" +
        " end;";
         CallableStatement cs=null;
            cs = OracleCon.getInstance().getConnexion().prepareCall(deleteetudiant);
            cs.setString(1,f);
            cs.setString(2,""+this.niveau);

        cs.registerOutParameter(3, OracleTypes.CURSOR);
        cs.execute();
        ResultSet rs = (ResultSet) cs.getObject(3);
            DefaultTableModel model=(DefaultTableModel) this.tablenotes.getModel();
        model.setRowCount(0);
        float somme=0;
       
        int nbr=0;
        int a;
        if(this.annee1.getText().isEmpty()){
        Date d=new Date();
         a=d.getYear();
        }
        else{
        a=Integer.parseInt(this.annee1.getText());
        }
        while(rs.next ()){
        if(Integer.parseInt(rs.getString("annee"))==a){
        Object[] row=new Object[4];
        row[0]=rs.getString("nom_module");
        row[1]=rs.getString("nombre_element");
        nbr+=1;
        row[2]=rs.getFloat("note_module");
        somme +=rs.getFloat("note_module");
        row[3]=rs.getString("annee");
        model.addRow(row);        
        }
}
        
        this.resultat.setText(""+(float)(somme/nbr));
        
 

        
     }
     
     
     
     
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annee1;
    private javax.swing.JComboBox<String> annees;
    private javax.swing.JComboBox<String> filieres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel resultat;
    private javax.swing.JTable tableetudiants;
    private javax.swing.JTable tablenotes;
    // End of variables declaration//GEN-END:variables
}
